namespace Spellbook.Services;

/// <summary>图标定义:Key 与 Assets/Icons/{Key}.png 文件名一致。</summary>
public record IconDef(string Key, string DisplayName, string Category);

/// <summary>
/// 内置图标清单(手绘风):
/// 法术类出自 Painterly Spell Icons(J. W. Bjerk / eleazzaar,CC-BY 3.0),
/// 武器物品类出自 Fantasy Icon Pack(Ravenmore,CC-BY 3.0)。
/// 顺序即选择器展示顺序(按类别分块);第一个 book 为默认图标。
/// </summary>
public static class IconLibrary
{
    public static readonly IReadOnlyList<IconDef> All = new IconDef[]
    {
        // ---- 物品 ----
        new("book", "法术书", "物品"),
        // ---- 武器 ----
        new("sword", "利剑", "武器"),
        new("wood-sword", "木剑", "武器"),
        new("dagger", "匕首", "武器"),
        new("axe", "战斧", "武器"),
        new("broad-axe", "阔斧", "武器"),
        new("double-axe", "双刃斧", "武器"),
        new("great-axe", "巨型双刃斧", "武器"),
        new("warhammer", "战锤", "武器"),
        new("bow", "长弓", "武器"),
        new("spear", "长矛", "武器"),
        new("wand", "魔杖", "武器"),
        // ---- 防具 ----
        new("shield-tower", "塔盾", "防具"),
        new("shield-round", "圆盾", "防具"),
        new("helmet", "头盔", "防具"),
        new("chestplate", "胸甲", "防具"),
        // ---- 物品 ----
        new("scroll", "卷轴", "物品"),
        new("map", "藏宝图", "物品"),
        new("coin", "金币", "物品"),
        new("backpack", "行囊", "物品"),
        new("envelope", "信件", "物品"),
        new("tools", "工匠工具", "物品"),
        new("heart", "生命之心", "物品"),
        new("gem-red", "红宝石", "物品"),
        new("gem-blue", "蓝宝石", "物品"),
        new("gem-green", "绿宝石", "物品"),
        new("potion-red", "红色药水", "物品"),
        new("potion-blue", "蓝色药水", "物品"),
        new("potion-green", "绿色药水", "物品"),
        // ---- 火焰 ----
        new("fireball", "火球术", "火焰"),
        new("fireball-blue", "蓝焰火球", "火焰"),
        new("fireball-acid", "酸蚀火球", "火焰"),
        new("fireball-shadow", "暗影火球", "火焰"),
        new("explosion", "爆裂术", "火焰"),
        new("explosion-orange", "烈焰爆炸", "火焰"),
        new("fire-arrows", "火焰箭", "火焰"),
        new("fire-shield", "炎之护盾", "火焰"),
        new("fire-needles", "火针术", "火焰"),
        new("fire-haste", "烈焰疾行", "火焰"),
        new("beam-orange", "橙焰射线", "火焰"),
        new("beam-red", "赤红射线", "火焰"),
        new("enchant-orange", "橙焰附魔", "火焰"),
        new("enchant-red", "赤红附魔", "火焰"),
        new("fog-orange", "橙焰迷雾", "火焰"),
        new("lighting-fire", "烈焰雷光", "火焰"),
        new("slice-orange", "烈焰斩击", "火焰"),
        new("wind-red", "赤红罡风", "火焰"),
        // ---- 冰霜 ----
        new("frostbolt", "寒冰箭", "冰霜"),
        new("ice-crystal", "冰晶术", "冰霜"),
        new("ice-jade", "翡翠寒冰", "冰霜"),
        new("water-rip", "激流撕裂", "冰霜"),
        new("water-fog", "水雾术", "冰霜"),
        new("beam-sky", "天蓝射线", "冰霜"),
        new("enchant-sky", "天蓝附魔", "冰霜"),
        new("explosion-sky", "寒霜爆炸", "冰霜"),
        new("fire-arrows-sky", "寒冰箭雨", "冰霜"),
        new("fog-blue", "蔚蓝迷雾", "冰霜"),
        new("fog-sky", "天蓝迷雾", "冰霜"),
        new("needles-blue", "寒冰棘刺", "冰霜"),
        new("needles-sky", "天蓝棘刺", "冰霜"),
        new("rip-sky", "寒霜撕裂", "冰霜"),
        new("slice-sky", "寒霜斩击", "冰霜"),
        // ---- 风雷 ----
        new("lightning", "闪电束", "风雷"),
        new("lightning-jade", "翠雷", "风雷"),
        new("lightning-orange", "橙雷", "风雷"),
        new("lightning-purple", "紫电", "风雷"),
        new("thunder-light", "雷光术", "风雷"),
        new("wind-blade", "风刃", "风雷"),
        new("wind-sky", "天风", "风雷"),
        new("air-burst", "气爆术", "风雷"),
        new("wind-grasp", "风之攫取", "风雷"),
        new("air-burst-jade", "翡翠气爆", "风雷"),
        new("air-burst-magenta", "魔紫气爆", "风雷"),
        new("air-burst-sky", "天蓝气爆", "风雷"),
        new("fog-air", "风息迷雾", "风雷"),
        new("haste-sky", "疾风加速", "风雷"),
        new("lighting-sky", "天雷之光", "风雷"),
        new("wind-grasp-sky", "天蓝风缚", "风雷"),
        // ---- 奥术 ----
        new("arcane-beam", "奥术射线", "奥术"),
        new("magic-beam", "魔光射线", "奥术"),
        new("enchant", "附魔术", "奥术"),
        new("rune", "符文术", "奥术"),
        new("rune-orange", "烈焰符文", "奥术"),
        new("rune-purple", "暗紫符文", "奥术"),
        new("arcane-link", "奥术链接", "奥术"),
        new("arcane-light", "秘法辉光", "奥术"),
        new("haste", "加速术", "奥术"),
        new("beam-blue", "蔚蓝射线", "奥术"),
        new("enchant-blue", "蔚蓝附魔", "奥术"),
        new("enchant-magenta", "魔紫附魔", "奥术"),
        new("explosion-magenta", "魔紫爆炸", "奥术"),
        new("explosion-royal", "秘法爆炸", "奥术"),
        new("fire-arrows-magenta", "魔紫箭雨", "奥术"),
        new("fire-arrows-royal", "秘法箭雨", "奥术"),
        new("light-magenta", "魔紫辉光", "奥术"),
        new("link-blue", "蔚蓝链接", "奥术"),
        new("needles-royal", "秘法棘刺", "奥术"),
        new("runes-blue", "蔚蓝符文", "奥术"),
        new("wind-grasp-magenta", "魔紫风缚", "奥术"),
        new("wind-magenta", "魔紫罡风", "奥术"),
        // ---- 神圣 ----
        new("heal", "治疗术", "神圣"),
        new("heal-sky", "天光治疗", "神圣"),
        new("heal-jade", "翡翠治疗", "神圣"),
        new("holy-light", "圣光术", "神圣"),
        new("spirit-shield", "灵魂护盾", "神圣"),
        new("spirit-link", "灵魂链接", "神圣"),
        new("spirit-slice", "灵魂斩", "神圣"),
        new("light-air-fire", "圣火辉光", "神圣"),
        new("light-blue", "蔚蓝辉光", "神圣"),
        new("light-jade", "翡翠辉光", "神圣"),
        // ---- 暗影 ----
        new("cursed-eye", "邪眼", "暗影"),
        new("blood-eye", "血瞳", "暗影"),
        new("horror", "恐惧术", "暗影"),
        new("horror-red", "血色恐惧", "暗影"),
        new("shadow-beam", "暗影射线", "暗影"),
        new("shadow-enchant", "邪化附魔", "暗影"),
        new("shadow-fog", "魅影迷雾", "暗影"),
        new("shadow-light", "幽光", "暗影"),
        new("horror-acid", "剧毒惊惧", "暗影"),
        new("lighting-eerie", "幽邃雷光", "暗影"),
        new("link-eerie", "幽邃链接", "暗影"),
        new("rip-magenta", "暗影撕裂", "暗影"),
        new("shielding-eerie", "暗影护体", "暗影"),
        new("vines-eerie", "幽邃藤蔓", "暗影"),
        new("wild-eerie", "幽邃野性", "暗影"),
        new("wind-grasp-eerie", "幽邃风缚", "暗影"),
        // ---- 自然 ----
        new("leaf", "生命之叶", "自然"),
        new("leaf-acid", "酸叶术", "自然"),
        new("leaf-autumn", "秋叶", "自然"),
        new("vine", "缠绕藤蔓", "自然"),
        new("vine-poison", "毒藤", "自然"),
        new("wild", "野性呼唤", "自然"),
        new("wild-orange", "野性之怒", "自然"),
        new("poison-needles", "毒棘", "自然"),
        new("poison-fog", "毒雾", "自然"),
        new("acid-slice", "酸蚀斩", "自然"),
        new("acid-rip", "酸性撕裂", "自然"),
        new("beam-acid", "酸蚀射线", "自然"),
        new("beam-jade", "翡翠射线", "自然"),
        new("enchant-acid", "酸蚀附魔", "自然"),
        new("enchant-jade", "翡翠附魔", "自然"),
        new("fire-arrows-jade", "翡翠箭雨", "自然"),
        new("leaf-royal", "秘法之叶", "自然"),
        new("lighting-acid", "酸蚀雷光", "自然"),
        new("rip-jade", "翡翠撕裂", "自然"),
        new("vines-plain", "原野藤蔓", "自然"),
        new("wild-acid", "剧毒野性", "自然"),
        new("wind-grasp-acid", "毒风之缚", "自然"),
        // ---- 守护 ----
        new("protect", "皇家守护", "守护"),
        new("protect-fire", "烈焰守护", "守护"),
        new("protect-nature", "自然守护", "守护"),
        new("protect-sky", "天空守护", "守护"),
        new("protect-shadow", "暗影守护", "守护"),
        new("protect-acid", "毒抗守护", "守护"),
        new("shield-acid", "酸蚀护盾", "守护"),
        new("protect-blue", "蔚蓝守护", "守护"),
        new("protect-magenta", "魔纹守护", "守护"),
        new("protect-orange", "烈阳守护", "守护"),
        // ---- 大地 ----
        new("rock", "岩石拳", "大地"),
        new("rock-lava", "熔岩之核", "大地"),
        new("rock-royal", "秘石", "大地"),
        new("rock-acid", "毒石", "大地"),
        new("rock-sky", "天石", "大地"),
    };
}
